version: 2
jobs:
  build:
    working_directory: ~/graphql-cli-prepare
    docker:
      - image: circleci/node:latest@sha256:d3975de072921759f81a0997cd78e297acc5d0c99981091289051f5dabf50951
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: release
          command: yarn semantic-release || true